Repository TableauBits/Mellotron, pull requests merged in 2022-06, with the labels that each got.

#3 Création du dossier dist
  .gitignore
  dist/mellotron/3rdpartylicenses.txt
  dist/mellotron/favicon.ico
  dist/mellotron/index.html
  dist/mellotron/main.22568c1c4f979d70.js
  dist/mellotron/polyfills.e05b36a2f05cc9e3.js
  dist/mellotron/runtime.7b0b45b9344967ce.js
  dist/mellotron/styles.a65fa9cbccc99c62.css
Labels: enhancement, good first issue

#5 Mise à jour de la template de PR
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#13 Retrait de GitHub Pages
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  dist/mellotron/3rdpartylicenses.txt
  dist/mellotron/favicon.ico
  dist/mellotron/index.html
  dist/mellotron/main.22568c1c4f979d70.js
  dist/mellotron/polyfills.e05b36a2f05cc9e3.js
  dist/mellotron/runtime.7b0b45b9344967ce.js
  dist/mellotron/styles.a65fa9cbccc99c62.css
Labels: bug, invalid

#4 Ajout d'une table filtrable
  src/app/app.module.ts
  src/app/components/table-viewer/table-viewer.component.html
  src/app/components/table-viewer/table-viewer.component.spec.ts
  src/app/components/table-viewer/table-viewer.component.ts
Labels: enhancement

#19 Lecture de données JSON et affichage dans la table
  package-lock.json
  package.json
  src/app/components/table-viewer/table-viewer.component.html
  src/app/components/table-viewer/table-viewer.component.ts
  src/app/constants/constitutions.ts
  src/app/services/data-manager.service.spec.ts
  src/app/services/data-manager.service.ts
  src/assets/constitutions/X7.json
  tsconfig.json
Labels: enhancement, data

#22 Ajout des constitutions de la Saison 3
  src/app/components/table-viewer/table-viewer.component.html
  src/app/constants/constitutions.ts
  src/app/services/data-manager.service.ts
  src/assets/constitutions/C9.json
  src/assets/constitutions/X1.json
  src/assets/constitutions/X2.json
  src/assets/constitutions/X3.json
  src/assets/constitutions/X4.json
Labels: enhancement, data

#23 Formatage des champs de la table
  src/app/app.module.ts
  src/app/components/table-viewer/table-viewer.component.html
  src/app/components/table-viewer/table-viewer.component.scss
  src/app/components/table-viewer/table-viewer.component.ts
  src/app/services/data-manager.service.ts
  src/assets/constitutions/C9.json
  src/assets/constitutions/X1.json
  src/assets/constitutions/X2.json
  src/assets/constitutions/X3.json
  src/assets/constitutions/X4.json
Labels: enhancement, data

#26 Classer les chansons par ordre croissant/décroissant en fonction d'un champ
  src/app/app.module.ts
  src/app/components/table-viewer/table-viewer.component.html
  src/app/components/table-viewer/table-viewer.component.ts
Labels: enhancement

#30 Colonnes à présent ré ordonnables
  src/app/app.module.ts
  src/app/components/table-viewer/table-viewer.component.html
  src/app/components/table-viewer/table-viewer.component.ts
Labels: enhancement

#32 Ajout des données X5 et X6
  src/app/constants/constitutions.ts
  src/assets/constitutions/X5.json
  src/assets/constitutions/X6.json
Labels: data

#31 Conservation de l'ordre des colonnes dans le `localStorage`
  src/app/components/table-viewer/table-viewer.component.ts
  src/app/constants/local-storage.ts
  src/app/services/local-storage.service.ts
Labels: enhancement
