Repository TableauBits/Mellotron, pull requests merged in 2024-01, with the labels that each got.

#67 Retrait du port 3000 du script `kalimba.js`
  kalimba.js
Labels: bug, communication

#68 Retrait du fichier `pnpm-lock.yaml`
  pnpm-lock.yaml
Labels: bug, dependencies

#66 Recherche non sensible aux accents
  src/app/constants/table.ts
Labels: enhancement
